apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    intent: apps
#   requirements:
#     # - key: "topology.kubernetes.io/zone"
#     #   operator: In
#     #   values: [${azs}]
#     - key: "karpenter.sh/capacity-type"
#       operator: In
#       values: ["spot", "on-demand"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: "aws005-preprod-test-eks-managed-ondemand"
    tags:
      accountingEC2Tag: KarpenterDevEnvironmentEC2
    subnetSelector:
      Name: "aws005-preprod-test-vpc-private*"
    securityGroupSelector:
      kubernetes.io/cluster/aws005-preprod-test-eks: 'owned'
  ttlSecondsAfterEmpty: 120
